In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('insurance.csv')

In [4]:
df.shape

(1338, 7)

In [5]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [6]:
df.replace([' ' , '?', 'nil' , 'na'] ,np.nan)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [7]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [8]:
df_nums = df.select_dtypes(include = 'number')

In [9]:
df['charges'] = round(df['charges'] , 2)

In [10]:
df

      age     sex     bmi  children smoker     region   charges
0      19  female  27.900         0    yes  southwest  16884.92
1      18    male  33.770         1     no  southeast   1725.55
2      28    male  33.000         3     no  southeast   4449.46
3      33    male  22.705         0     no  northwest  21984.47
4      32    male  28.880         0     no  northwest   3866.86
...   ...     ...     ...       ...    ...        ...       ...
1333   50    male  30.970         3     no  northwest  10600.55
1334   18  female  31.920         0     no  northeast   2205.98
1335   18  female  36.850         0     no  southeast   1629.83
1336   21  female  25.800         0     no  southwest   2007.94
1337   61  female  29.070         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [11]:
x = df.drop('charges' , axis = 1)
y = df['charges']

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state= 40)

In [13]:
x_train

      age     sex     bmi  children smoker     region
737    26    male  23.700         2     no  southwest
369    18    male  30.400         3     no  northeast
284    52  female  31.200         0     no  southwest
1302   25  female  20.800         1     no  southwest
958    43    male  34.960         1    yes  northeast
...   ...     ...     ...       ...    ...        ...
1330   57  female  25.740         2     no  southeast
1016   19  female  24.605         1     no  northwest
165    47    male  28.215         4     no  northeast
7      37  female  27.740         3     no  northwest
219    24  female  23.210         0     no  southeast

[1070 rows x 6 columns]

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
encode = OneHotEncoder(sparse_output= False , drop= 'first')

In [16]:
x_train_enco = encode.fit_transform(x_train.select_dtypes(include= 'object'))
x_test_enco = encode.transform(x_test.select_dtypes(include='object'))

In [17]:
x_train_dataset = pd.DataFrame(x_train_enco , columns= encode.get_feature_names_out())
x_test_dataset = pd.DataFrame(x_test_enco , columns= encode.get_feature_names_out())

In [18]:
X_train = pd.concat([x_train_dataset , x_train.reset_index().select_dtypes(exclude= 'object')] , axis = 1)
X_test = pd.concat([x_test_dataset , x_test.reset_index().select_dtypes(exclude= 'object')] , axis = 1)

In [19]:
X_test

,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest,index,age,bmi,children
0,0.0,0.0,0.0,1.0,0.0,1099,25,33.990,1
1,1.0,1.0,0.0,1.0,0.0,759,18,38.170,0
2,0.0,0.0,0.0,0.0,1.0,215,41,37.100,2
3,1.0,0.0,0.0,1.0,0.0,903,49,36.850,0
4,0.0,1.0,0.0,0.0,0.0,989,24,20.520,0
...,...,...,...,...,...,...,...,...,...
263,1.0,0.0,0.0,1.0,0.0,408,38,21.120,3
264,0.0,0.0,0.0,0.0,1.0,466,60,28.700,1
265,0.0,0.0,0.0,0.0,0.0,724,50,27.075,1
266,1.0,0.0,1.0,0.0,0.0,693,24,23.655,0
267,1.0,1.0,0.0,0.0,0.0,738,23,31.730,3

In [20]:
X_train.drop('index' , axis = 1 , inplace= True)
X_test.drop('index' , axis = 1 , inplace= True)

In [21]:
X_train

,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest,age,bmi,children
0,1.0,0.0,0.0,0.0,1.0,26,23.700,2
1,1.0,0.0,0.0,0.0,0.0,18,30.400,3
2,0.0,0.0,0.0,0.0,1.0,52,31.200,0
3,0.0,0.0,0.0,0.0,1.0,25,20.800,1
4,1.0,1.0,0.0,0.0,0.0,43,34.960,1
...,...,...,...,...,...,...,...,...
1065,0.0,0.0,0.0,1.0,0.0,57,25.740,2
1066,0.0,0.0,1.0,0.0,0.0,19,24.605,1
1067,1.0,0.0,0.0,0.0,0.0,47,28.215,4
1068,0.0,0.0,1.0,0.0,0.0,37,27.740,3
1069,0.0,0.0,0.0,1.0,0.0,24,23.210,0

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
scaler = StandardScaler()

In [24]:
y_train_scaled = scaler.fit_transform(y_train.values.reshape(-1,1))
y_test_scaled = scaler.transform(y_test.values.reshape(-1,1))

In [25]:
X_train

,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest,age,bmi,children
0,1.0,0.0,0.0,0.0,1.0,26,23.700,2
1,1.0,0.0,0.0,0.0,0.0,18,30.400,3
2,0.0,0.0,0.0,0.0,1.0,52,31.200,0
3,0.0,0.0,0.0,0.0,1.0,25,20.800,1
4,1.0,1.0,0.0,0.0,0.0,43,34.960,1
...,...,...,...,...,...,...,...,...
1065,0.0,0.0,0.0,1.0,0.0,57,25.740,2
1066,0.0,0.0,1.0,0.0,0.0,19,24.605,1
1067,1.0,0.0,0.0,0.0,0.0,47,28.215,4
1068,0.0,0.0,1.0,0.0,0.0,37,27.740,3
1069,0.0,0.0,0.0,1.0,0.0,24,23.210,0

In [26]:
y_train

737      3484.33
369      3481.87
284      9625.92
1302     3208.79
958     41034.22
          ...
1330    12629.17
1016     2709.24
165     10407.09
7        7281.51
219     25081.77
Name: charges, Length: 1070, dtype: float64

In [27]:
y_train = pd.DataFrame(y_train_scaled , columns= ['charges'])
y_test = pd.DataFrame(y_test_scaled , columns= ['charges'])

In [28]:
import torch
from torch import nn

In [29]:
X_train_tensor = torch.tensor(X_train.values , dtype= torch.float32)
X_test_tensor = torch.tensor(X_test.values, dtype= torch.float32)

In [30]:
y_train_tensor = torch.tensor(y_train.values , dtype= torch.float32)
y_test_tensor = torch.tensor(y_test.values ,dtype= torch.float32)

In [31]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(in_features=8 , out_features=1)
  def forward(self , x):
    return self.linear(x)

In [32]:
model = LinearRegressionModel()
loss_fn = torch.nn.MSELoss();
optimizer = torch.optim.SGD(model.parameters() , lr = 0.0001)

In [33]:
for i in range(0, 10000):
  model.train()
  optimizer.zero_grad()
  outputs = model(X_train_tensor)
  loss = loss_fn(outputs , y_train_tensor)
  loss.backward()
  optimizer.step()
  if i % 10 == 0:
    print(f'Epoch: [{i+1}/10000] , Loss: {loss}')

Epoch: [1/10000] , Loss: 6.362669944763184
Epoch: [11/10000] , Loss: 3.3854739665985107
Epoch: [21/10000] , Loss: 2.722280263900757
Epoch: [31/10000] , Loss: 2.251328945159912
Epoch: [41/10000] , Loss: 1.916852593421936
Epoch: [51/10000] , Loss: 1.6792612075805664
Epoch: [61/10000] , Loss: 1.5104501247406006
Epoch: [71/10000] , Loss: 1.3904670476913452
Epoch: [81/10000] , Loss: 1.3051477670669556
Epoch: [91/10000] , Loss: 1.2444366216659546
Epoch: [101/10000] , Loss: 1.201195478439331
Epoch: [111/10000] , Loss: 1.1703565120697021
Epoch: [121/10000] , Loss: 1.1483221054077148
Epoch: [131/10000] , Loss: 1.1325381994247437
Epoch: [141/10000] , Loss: 1.1211920976638794
Epoch: [151/10000] , Loss: 1.112995982170105
Epoch: [161/10000] , Loss: 1.1070364713668823
Epoch: [171/10000] , Loss: 1.1026649475097656
Epoch: [181/10000] , Loss: 1.0994206666946411
Epoch: [191/10000] , Loss: 1.0969767570495605
Epoch: [201/10000] , Loss: 1.0951013565063477
Epoch: [211/10000] , Loss: 1.0936293601989746
Epoch: [221/10000] , Loss: 1.0924441814422607
Epoch: [231/10000] , Loss: 1.09146249294281
Epoch: [241/10000] , Loss: 1.090625286102295
Epoch: [251/10000] , Loss: 1.089890956878662
Epoch: [261/10000] , Loss: 1.089229702949524
Epoch: [271/10000] , Loss: 1.0886204242706299
Epoch: [281/10000] , Loss: 1.0880481004714966
Epoch: [291/10000] , Loss: 1.0875022411346436
Epoch: [301/10000] , Loss: 1.08697509765625
Epoch: [311/10000] , Loss: 1.0864616632461548
Epoch: [321/10000] , Loss: 1.0859577655792236
Epoch: [331/10000] , Loss: 1.085460901260376
Epoch: [341/10000] , Loss: 1.0849688053131104
Epoch: [351/10000] , Loss: 1.0844806432724
Epoch: [361/10000] , Loss: 1.0839951038360596
Epoch: [371/10000] , Loss: 1.0835115909576416
Epoch: [381/10000] , Loss: 1.0830297470092773
Epoch: [391/10000] , Loss: 1.082548975944519
Epoch: [401/10000] , Loss: 1.0820691585540771
Epoch: [411/10000] , Loss: 1.081590175628662
Epoch: [421/10000] , Loss: 1.0811119079589844
Epoch: [431/10000] , Loss: 1.0806341171264648
Epoch: [441/10000] , Loss: 1.0801568031311035
Epoch: [451/10000] , Loss: 1.0796802043914795
Epoch: [461/10000] , Loss: 1.0792038440704346
Epoch: [471/10000] , Loss: 1.0787280797958374
Epoch: [481/10000] , Loss: 1.0782524347305298
Epoch: [491/10000] , Loss: 1.0777771472930908
Epoch: [501/10000] , Loss: 1.0773024559020996
Epoch: [511/10000] , Loss: 1.076828122138977
Epoch: [521/10000] , Loss: 1.0763540267944336
Epoch: [531/10000] , Loss: 1.0758804082870483
Epoch: [541/10000] , Loss: 1.0754071474075317
Epoch: [551/10000] , Loss: 1.0749341249465942
Epoch: [561/10000] , Loss: 1.074461579322815
Epoch: [571/10000] , Loss: 1.0739891529083252
Epoch: [581/10000] , Loss: 1.0735173225402832
Epoch: [591/10000] , Loss: 1.0730458498001099
Epoch: [601/10000] , Loss: 1.0725747346878052
Epoch: [611/10000] , Loss: 1.0721038579940796
Epoch: [621/10000] , Loss: 1.071633219718933
Epoch: [631/10000] , Loss: 1.0711630582809448
Epoch: [641/10000] , Loss: 1.0706932544708252
Epoch: [651/10000] , Loss: 1.0702236890792847
Epoch: [661/10000] , Loss: 1.069754719734192
Epoch: [671/10000] , Loss: 1.0692858695983887
Epoch: [681/10000] , Loss: 1.068817377090454
Epoch: [691/10000] , Loss: 1.0683493614196777
Epoch: [701/10000] , Loss: 1.0678815841674805
Epoch: [711/10000] , Loss: 1.0674142837524414
Epoch: [721/10000] , Loss: 1.066947102546692
Epoch: [731/10000] , Loss: 1.0664803981781006
Epoch: [741/10000] , Loss: 1.066014051437378
Epoch: [751/10000] , Loss: 1.0655479431152344
Epoch: [761/10000] , Loss: 1.0650824308395386
Epoch: [771/10000] , Loss: 1.0646169185638428
Epoch: [781/10000] , Loss: 1.0641520023345947
Epoch: [791/10000] , Loss: 1.0636874437332153
Epoch: [801/10000] , Loss: 1.063223123550415
Epoch: [811/10000] , Loss: 1.0627590417861938
Epoch: [821/10000] , Loss: 1.0622954368591309
Epoch: [831/10000] , Loss: 1.061832308769226
Epoch: [841/10000] , Loss: 1.0613692998886108
Epoch: [851/10000] , Loss: 1.0609066486358643
Epoch: [861/10000] , Loss: 1.0604445934295654
Epoch: [871/10000] , Loss: 1.0599825382232666
Epoch: [881/10000] , Loss: 1.059520959854126
Epoch: [891/10000] , Loss: 1.0590596199035645
Epoch: [901/10000] , Loss: 1.0585988759994507
Epoch: [911/10000] , Loss: 1.0581382513046265
Epoch: [921/10000] , Loss: 1.057677984237671
Epoch: [931/10000] , Loss: 1.0572179555892944
Epoch: [941/10000] , Loss: 1.0567586421966553
Epoch: [951/10000] , Loss: 1.0562993288040161
Epoch: [961/10000] , Loss: 1.0558403730392456
Epoch: [971/10000] , Loss: 1.0553817749023438
Epoch: [981/10000] , Loss: 1.0549235343933105
Epoch: [991/10000] , Loss: 1.054465651512146
Epoch: [1001/10000] , Loss: 1.0540080070495605
Epoch: [1011/10000] , Loss: 1.0535508394241333
Epoch: [1021/10000] , Loss: 1.0530939102172852
Epoch: [1031/10000] , Loss: 1.0526374578475952
Epoch: [1041/10000] , Loss: 1.0521811246871948
Epoch: [1051/10000] , Loss: 1.0517253875732422
Epoch: [1061/10000] , Loss: 1.0512698888778687
Epoch: [1071/10000] , Loss: 1.0508145093917847
Epoch: [1081/10000] , Loss: 1.0503597259521484
Epoch: [1091/10000] , Loss: 1.0499050617218018
Epoch: [1101/10000] , Loss: 1.0494508743286133
Epoch: [1111/10000] , Loss: 1.048996925354004
Epoch: [1121/10000] , Loss: 1.0485434532165527
Epoch: [1131/10000] , Loss: 1.0480902194976807
Epoch: [1141/10000] , Loss: 1.0476372241973877
Epoch: [1151/10000] , Loss: 1.0471845865249634
Epoch: [1161/10000] , Loss: 1.0467324256896973
Epoch: [1171/10000] , Loss: 1.0462805032730103
Epoch: [1181/10000] , Loss: 1.0458288192749023
Epoch: [1191/10000] , Loss: 1.045377492904663
Epoch: [1201/10000] , Loss: 1.0449265241622925
Epoch: [1211/10000] , Loss: 1.0444759130477905
Epoch: [1221/10000] , Loss: 1.0440256595611572
Epoch: [1231/10000] , Loss: 1.0435757637023926
Epoch: [1241/10000] , Loss: 1.043126106262207
Epoch: [1251/10000] , Loss: 1.0426768064498901
Epoch: [1261/10000] , Loss: 1.042227864265442
Epoch: [1271/10000] , Loss: 1.0417790412902832
Epoch: [1281/10000] , Loss: 1.0413308143615723
Epoch: [1291/10000] , Loss: 1.0408828258514404
Epoch: [1301/10000] , Loss: 1.0404350757598877
Epoch: [1311/10000] , Loss: 1.0399876832962036
Epoch: [1321/10000] , Loss: 1.0395407676696777
Epoch: [1331/10000] , Loss: 1.039094090461731
Epoch: [1341/10000] , Loss: 1.0386476516723633
Epoch: [1351/10000] , Loss: 1.0382013320922852
Epoch: [1361/10000] , Loss: 1.0377557277679443
Epoch: [1371/10000] , Loss: 1.0373103618621826
Epoch: [1381/10000] , Loss: 1.036865234375
Epoch: [1391/10000] , Loss: 1.036420464515686
Epoch: [1401/10000] , Loss: 1.0359758138656616
Epoch: [1411/10000] , Loss: 1.035531759262085
Epoch: [1421/10000] , Loss: 1.0350878238677979
Epoch: [1431/10000] , Loss: 1.034644365310669
Epoch: [1441/10000] , Loss: 1.0342010259628296
Epoch: [1451/10000] , Loss: 1.033758282661438
Epoch: [1461/10000] , Loss: 1.0333157777786255
Epoch: [1471/10000] , Loss: 1.0328733921051025
Epoch: [1481/10000] , Loss: 1.0324316024780273
Epoch: [1491/10000] , Loss: 1.0319899320602417
Epoch: [1501/10000] , Loss: 1.0315486192703247
Epoch: [1511/10000] , Loss: 1.0311076641082764
Epoch: [1521/10000] , Loss: 1.0306671857833862
Epoch: [1531/10000] , Loss: 1.0302268266677856
Epoch: [1541/10000] , Loss: 1.0297867059707642
Epoch: [1551/10000] , Loss: 1.0293469429016113
Epoch: [1561/10000] , Loss: 1.0289076566696167
Epoch: [1571/10000] , Loss: 1.0284686088562012
Epoch: [1581/10000] , Loss: 1.0280296802520752
Epoch: [1591/10000] , Loss: 1.027591347694397
Epoch: [1601/10000] , Loss: 1.0271532535552979
Epoch: [1611/10000] , Loss: 1.0267153978347778
Epoch: [1621/10000] , Loss: 1.0262778997421265
Epoch: [1631/10000] , Loss: 1.0258405208587646
Epoch: [1641/10000] , Loss: 1.0254037380218506
Epoch: [1651/10000] , Loss: 1.0249673128128052
Epoch: [1661/10000] , Loss: 1.0245308876037598
Epoch: [1671/10000] , Loss: 1.0240949392318726
Epoch: [1681/10000] , Loss: 1.023659110069275
Epoch: [1691/10000] , Loss: 1.023223876953125
Epoch: [1701/10000] , Loss: 1.0227888822555542
Epoch: [1711/10000] , Loss: 1.022354245185852
Epoch: [1721/10000] , Loss: 1.0219199657440186
Epoch: [1731/10000] , Loss: 1.0214858055114746
Epoch: [1741/10000] , Loss: 1.0210521221160889
Epoch: [1751/10000] , Loss: 1.0206184387207031
Epoch: [1761/10000] , Loss: 1.0201853513717651
Epoch: [1771/10000] , Loss: 1.0197526216506958
Epoch: [1781/10000] , Loss: 1.0193201303482056
Epoch: [1791/10000] , Loss: 1.0188877582550049
Epoch: [1801/10000] , Loss: 1.0184558629989624
Epoch: [1811/10000] , Loss: 1.0180243253707886
Epoch: [1821/10000] , Loss: 1.0175929069519043
Epoch: [1831/10000] , Loss: 1.0171620845794678
Epoch: [1841/10000] , Loss: 1.0167313814163208
Epoch: [1851/10000] , Loss: 1.016300916671753
Epoch: [1861/10000] , Loss: 1.0158708095550537
Epoch: [1871/10000] , Loss: 1.0154410600662231
Epoch: [1881/10000] , Loss: 1.0150115489959717
Epoch: [1891/10000] , Loss: 1.0145823955535889
Epoch: [1901/10000] , Loss: 1.0141535997390747
Epoch: [1911/10000] , Loss: 1.0137250423431396
Epoch: [1921/10000] , Loss: 1.0132967233657837
Epoch: [1931/10000] , Loss: 1.0128687620162964
Epoch: [1941/10000] , Loss: 1.0124411582946777
Epoch: [1951/10000] , Loss: 1.0120137929916382
Epoch: [1961/10000] , Loss: 1.0115867853164673
Epoch: [1971/10000] , Loss: 1.011160135269165
Epoch: [1981/10000] , Loss: 1.0107336044311523
Epoch: [1991/10000] , Loss: 1.0103075504302979
Epoch: [2001/10000] , Loss: 1.009881615638733
Epoch: [2011/10000] , Loss: 1.0094562768936157
Epoch: [2021/10000] , Loss: 1.0090309381484985
Epoch: [2031/10000] , Loss: 1.00860595703125
Epoch: [2041/10000] , Loss: 1.0081813335418701
Epoch: [2051/10000] , Loss: 1.0077570676803589
Epoch: [2061/10000] , Loss: 1.0073330402374268
Epoch: [2071/10000] , Loss: 1.0069093704223633
Epoch: [2081/10000] , Loss: 1.006485939025879
Epoch: [2091/10000] , Loss: 1.0060627460479736
Epoch: [2101/10000] , Loss: 1.005639910697937
Epoch: [2111/10000] , Loss: 1.0052175521850586
Epoch: [2121/10000] , Loss: 1.0047953128814697
Epoch: [2131/10000] , Loss: 1.0043734312057495
Epoch: [2141/10000] , Loss: 1.0039516687393188
Epoch: [2151/10000] , Loss: 1.0035303831100464
Epoch: [2161/10000] , Loss: 1.0031092166900635
Epoch: [2171/10000] , Loss: 1.0026885271072388
Epoch: [2181/10000] , Loss: 1.0022680759429932
Epoch: [2191/10000] , Loss: 1.0018478631973267
Epoch: [2201/10000] , Loss: 1.0014280080795288
Epoch: [2211/10000] , Loss: 1.0010085105895996
Epoch: [2221/10000] , Loss: 1.0005892515182495
Epoch: [2231/10000] , Loss: 1.0001702308654785
Epoch: [2241/10000] , Loss: 0.999751627445221
Epoch: [2251/10000] , Loss: 0.9993332624435425
Epoch: [2261/10000] , Loss: 0.9989151954650879
Epoch: [2271/10000] , Loss: 0.9984973669052124
Epoch: [2281/10000] , Loss: 0.9980799555778503
Epoch: [2291/10000] , Loss: 0.9976628422737122
Epoch: [2301/10000] , Loss: 0.9972460269927979
Epoch: [2311/10000] , Loss: 0.9968292713165283
Epoch: [2321/10000] , Loss: 0.9964130520820618
Epoch: [2331/10000] , Loss: 0.99599689245224
Epoch: [2341/10000] , Loss: 0.9955812692642212
Epoch: [2351/10000] , Loss: 0.9951658844947815
Epoch: [2361/10000] , Loss: 0.9947506189346313
Epoch: [2371/10000] , Loss: 0.9943358302116394
Epoch: [2381/10000] , Loss: 0.9939212203025818
Epoch: [2391/10000] , Loss: 0.9935070276260376
Epoch: [2401/10000] , Loss: 0.9930930137634277
Epoch: [2411/10000] , Loss: 0.9926791787147522
Epoch: [2421/10000] , Loss: 0.9922658801078796
Epoch: [2431/10000] , Loss: 0.9918527603149414
Epoch: [2441/10000] , Loss: 0.9914399981498718
Epoch: [2451/10000] , Loss: 0.9910274744033813
Epoch: [2461/10000] , Loss: 0.9906150698661804
Epoch: [2471/10000] , Loss: 0.9902031421661377
Epoch: [2481/10000] , Loss: 0.9897916316986084
Epoch: [2491/10000] , Loss: 0.9893802404403687
Epoch: [2501/10000] , Loss: 0.988969087600708
Epoch: [2511/10000] , Loss: 0.9885583519935608
Epoch: [2521/10000] , Loss: 0.9881479144096375
Epoch: [2531/10000] , Loss: 0.9877376556396484
Epoch: [2541/10000] , Loss: 0.9873277544975281
Epoch: [2551/10000] , Loss: 0.986918032169342
Epoch: [2561/10000] , Loss: 0.9865087270736694
Epoch: [2571/10000] , Loss: 0.9860996007919312
Epoch: [2581/10000] , Loss: 0.9856908321380615
Epoch: [2591/10000] , Loss: 0.9852824211120605
Epoch: [2601/10000] , Loss: 0.9848741292953491
Epoch: [2611/10000] , Loss: 0.9844662547111511
Epoch: [2621/10000] , Loss: 0.9840586185455322
Epoch: [2631/10000] , Loss: 0.9836511611938477
Epoch: [2641/10000] , Loss: 0.9832441806793213
Epoch: [2651/10000] , Loss: 0.9828373789787292
Epoch: [2661/10000] , Loss: 0.9824308753013611
Epoch: [2671/10000] , Loss: 0.982024610042572
Epoch: [2681/10000] , Loss: 0.9816185832023621
Epoch: [2691/10000] , Loss: 0.9812130331993103
Epoch: [2701/10000] , Loss: 0.9808076024055481
Epoch: [2711/10000] , Loss: 0.9804025888442993
Epoch: [2721/10000] , Loss: 0.9799976944923401
Epoch: [2731/10000] , Loss: 0.9795931577682495
Epoch: [2741/10000] , Loss: 0.979188859462738
Epoch: [2751/10000] , Loss: 0.97878497838974
Epoch: [2761/10000] , Loss: 0.978381335735321
Epoch: [2771/10000] , Loss: 0.9779779314994812
Epoch: [2781/10000] , Loss: 0.97757488489151
Epoch: [2791/10000] , Loss: 0.9771720767021179
Epoch: [2801/10000] , Loss: 0.9767694473266602
Epoch: [2811/10000] , Loss: 0.976367175579071
Epoch: [2821/10000] , Loss: 0.975965142250061
Epoch: [2831/10000] , Loss: 0.9755635857582092
Epoch: [2841/10000] , Loss: 0.9751620292663574
Epoch: [2851/10000] , Loss: 0.974760890007019
Epoch: [2861/10000] , Loss: 0.9743599891662598
Epoch: [2871/10000] , Loss: 0.9739594459533691
Epoch: [2881/10000] , Loss: 0.9735591411590576
Epoch: [2891/10000] , Loss: 0.97315913438797
Epoch: [2901/10000] , Loss: 0.9727593660354614
Epoch: [2911/10000] , Loss: 0.972359836101532
Epoch: [2921/10000] , Loss: 0.9719606637954712
Epoch: [2931/10000] , Loss: 0.9715617299079895
Epoch: [2941/10000] , Loss: 0.9711630940437317
Epoch: [2951/10000] , Loss: 0.9707646369934082
Epoch: [2961/10000] , Loss: 0.9703665971755981
Epoch: [2971/10000] , Loss: 0.9699687361717224
Epoch: [2981/10000] , Loss: 0.9695711731910706
Epoch: [2991/10000] , Loss: 0.9691739082336426
Epoch: [3001/10000] , Loss: 0.9687769412994385
Epoch: [3011/10000] , Loss: 0.9683802723884583
Epoch: [3021/10000] , Loss: 0.9679837822914124
Epoch: [3031/10000] , Loss: 0.9675875902175903
Epoch: [3041/10000] , Loss: 0.9671916961669922
Epoch: [3051/10000] , Loss: 0.9667962193489075
Epoch: [3061/10000] , Loss: 0.9664008617401123
Epoch: [3071/10000] , Loss: 0.966005802154541
Epoch: [3081/10000] , Loss: 0.9656109809875488
Epoch: [3091/10000] , Loss: 0.9652164578437805
Epoch: [3101/10000] , Loss: 0.9648221731185913
Epoch: [3111/10000] , Loss: 0.9644282460212708
Epoch: [3121/10000] , Loss: 0.9640345573425293
Epoch: [3131/10000] , Loss: 0.9636410474777222
Epoch: [3141/10000] , Loss: 0.963248074054718
Epoch: [3151/10000] , Loss: 0.9628551602363586
Epoch: [3161/10000] , Loss: 0.9624626040458679
Epoch: [3171/10000] , Loss: 0.962070107460022
Epoch: [3181/10000] , Loss: 0.961678147315979
Epoch: [3191/10000] , Loss: 0.9612862467765808
Epoch: [3201/10000] , Loss: 0.9608947038650513
Epoch: [3211/10000] , Loss: 0.9605035185813904
Epoch: [3221/10000] , Loss: 0.9601125717163086
Epoch: [3231/10000] , Loss: 0.9597218036651611
Epoch: [3241/10000] , Loss: 0.9593313932418823
Epoch: [3251/10000] , Loss: 0.9589412808418274
Epoch: [3261/10000] , Loss: 0.958551287651062
Epoch: [3271/10000] , Loss: 0.9581615924835205
Epoch: [3281/10000] , Loss: 0.9577722549438477
Epoch: [3291/10000] , Loss: 0.9573830962181091
Epoch: [3301/10000] , Loss: 0.956994354724884
Epoch: [3311/10000] , Loss: 0.956605851650238
Epoch: [3321/10000] , Loss: 0.9562175273895264
Epoch: [3331/10000] , Loss: 0.9558295607566833
Epoch: [3341/10000] , Loss: 0.9554417729377747
Epoch: [3351/10000] , Loss: 0.9550543427467346
Epoch: [3361/10000] , Loss: 0.9546671509742737
Epoch: [3371/10000] , Loss: 0.9542800784111023
Epoch: [3381/10000] , Loss: 0.9538936018943787
Epoch: [3391/10000] , Loss: 0.9535070061683655
Epoch: [3401/10000] , Loss: 0.9531209468841553
Epoch: [3411/10000] , Loss: 0.9527350664138794
Epoch: [3421/10000] , Loss: 0.9523494839668274
Epoch: [3431/10000] , Loss: 0.9519640207290649
Epoch: [3441/10000] , Loss: 0.9515790343284607
Epoch: [3451/10000] , Loss: 0.951194167137146
Epoch: [3461/10000] , Loss: 0.9508096575737
Epoch: [3471/10000] , Loss: 0.950425386428833
Epoch: [3481/10000] , Loss: 0.9500413537025452
Epoch: [3491/10000] , Loss: 0.9496574997901917
Epoch: [3501/10000] , Loss: 0.9492740631103516
Epoch: [3511/10000] , Loss: 0.9488908648490906
Epoch: [3521/10000] , Loss: 0.9485078454017639
Epoch: [3531/10000] , Loss: 0.9481250643730164
Epoch: [3541/10000] , Loss: 0.9477426409721375
Epoch: [3551/10000] , Loss: 0.9473604559898376
Epoch: [3561/10000] , Loss: 0.9469785690307617
Epoch: [3571/10000] , Loss: 0.9465968608856201
Epoch: [3581/10000] , Loss: 0.9462154507637024
Epoch: [3591/10000] , Loss: 0.9458343386650085
Epoch: [3601/10000] , Loss: 0.9454535245895386
Epoch: [3611/10000] , Loss: 0.9450728893280029
Epoch: [3621/10000] , Loss: 0.9446925520896912
Epoch: [3631/10000] , Loss: 0.944312572479248
Epoch: [3641/10000] , Loss: 0.9439327716827393
Epoch: [3651/10000] , Loss: 0.9435531497001648
Epoch: [3661/10000] , Loss: 0.9431740045547485
Epoch: [3671/10000] , Loss: 0.942794919013977
Epoch: [3681/10000] , Loss: 0.9424160718917847
Epoch: [3691/10000] , Loss: 0.9420375823974609
Epoch: [3701/10000] , Loss: 0.9416593909263611
Epoch: [3711/10000] , Loss: 0.9412814378738403
Epoch: [3721/10000] , Loss: 0.9409036636352539
Epoch: [3731/10000] , Loss: 0.9405261278152466
Epoch: [3741/10000] , Loss: 0.9401488304138184
Epoch: [3751/10000] , Loss: 0.9397720098495483
Epoch: [3761/10000] , Loss: 0.9393952488899231
Epoch: [3771/10000] , Loss: 0.9390188455581665
Epoch: [3781/10000] , Loss: 0.938642680644989
Epoch: [3791/10000] , Loss: 0.9382667541503906
Epoch: [3801/10000] , Loss: 0.9378910660743713
Epoch: [3811/10000] , Loss: 0.9375154972076416
Epoch: [3821/10000] , Loss: 0.9371404647827148
Epoch: [3831/10000] , Loss: 0.9367656111717224
Epoch: [3841/10000] , Loss: 0.9363909363746643
Epoch: [3851/10000] , Loss: 0.9360164999961853
Epoch: [3861/10000] , Loss: 0.9356424808502197
Epoch: [3871/10000] , Loss: 0.9352685213088989
Epoch: [3881/10000] , Loss: 0.934894859790802
Epoch: [3891/10000] , Loss: 0.9345216155052185
Epoch: [3901/10000] , Loss: 0.9341485500335693
Epoch: [3911/10000] , Loss: 0.9337757229804993
Epoch: [3921/10000] , Loss: 0.9334030747413635
Epoch: [3931/10000] , Loss: 0.9330307841300964
Epoch: [3941/10000] , Loss: 0.9326587319374084
Epoch: [3951/10000] , Loss: 0.9322869777679443
Epoch: [3961/10000] , Loss: 0.931915283203125
Epoch: [3971/10000] , Loss: 0.9315440058708191
Epoch: [3981/10000] , Loss: 0.9311729073524475
Epoch: [3991/10000] , Loss: 0.9308021664619446
Epoch: [4001/10000] , Loss: 0.930431604385376
Epoch: [4011/10000] , Loss: 0.9300613403320312
Epoch: [4021/10000] , Loss: 0.9296911954879761
Epoch: [4031/10000] , Loss: 0.9293215870857239
Epoch: [4041/10000] , Loss: 0.9289519786834717
Epoch: [4051/10000] , Loss: 0.9285826683044434
Epoch: [4061/10000] , Loss: 0.9282135963439941
Epoch: [4071/10000] , Loss: 0.9278449416160583
Epoch: [4081/10000] , Loss: 0.9274762868881226
Epoch: [4091/10000] , Loss: 0.9271080493927002
Epoch: [4101/10000] , Loss: 0.9267399311065674
Epoch: [4111/10000] , Loss: 0.926372230052948
Epoch: [4121/10000] , Loss: 0.9260046482086182
Epoch: [4131/10000] , Loss: 0.9256373047828674
Epoch: [4141/10000] , Loss: 0.9252702593803406
Epoch: [4151/10000] , Loss: 0.9249035716056824
Epoch: [4161/10000] , Loss: 0.9245370626449585
Epoch: [4171/10000] , Loss: 0.9241708517074585
Epoch: [4181/10000] , Loss: 0.923804759979248
Epoch: [4191/10000] , Loss: 0.9234389066696167
Epoch: [4201/10000] , Loss: 0.9230735301971436
Epoch: [4211/10000] , Loss: 0.9227082133293152
Epoch: [4221/10000] , Loss: 0.9223431944847107
Epoch: [4231/10000] , Loss: 0.9219784140586853
Epoch: [4241/10000] , Loss: 0.9216140508651733
Epoch: [4251/10000] , Loss: 0.9212496876716614
Epoch: [4261/10000] , Loss: 0.9208855628967285
Epoch: [4271/10000] , Loss: 0.9205219745635986
Epoch: [4281/10000] , Loss: 0.9201583862304688