In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
from sklearn.preprocessing import Normalizer

In [2]:
X = [[-5, 2 ,6],[-9, 4,-7]]
normalize(X, norm = 'l1')

array([[-0.38461538,  0.15384615,  0.46153846],
       [-0.45      ,  0.2       , -0.35      ]])

In [3]:
normalize(X, norm ='l2')

array([[-0.62017367,  0.24806947,  0.74420841],
       [-0.7448453 ,  0.33104236, -0.57932412]])

In [4]:
normalize(X , norm = 'max')

array([[-0.83333333,  0.33333333,  1.        ],
       [-1.        ,  0.44444444, -0.77777778]])

In [5]:
normalize(X, norm = 'l1', axis = 1)

array([[-0.38461538,  0.15384615,  0.46153846],
       [-0.45      ,  0.2       , -0.35      ]])

In [6]:
normalize(X, norm ='l1', axis = 0)

array([[-0.35714286,  0.33333333,  0.46153846],
       [-0.64285714,  0.66666667, -0.53846154]])

In [7]:
normalize(X, norm ='l2' , axis = 0)

array([[-0.48564293,  0.4472136 ,  0.65079137],
       [-0.87415728,  0.89442719, -0.7592566 ]])

In [8]:
normalize(X , norm ='max' , axis= 0)

array([[-0.55555556,  0.5       ,  0.85714286],
       [-1.        ,  1.        , -1.        ]])

In [9]:
arr = np.array([[2, 4 , -9] ,[4, 6, -7] ,[12, -9, 0]])

In [10]:
arr

array([[ 2,  4, -9],
       [ 4,  6, -7],
       [12, -9,  0]])

In [11]:
norm = Normalizer(norm = 'l1')
norm.transform(arr)

array([[ 0.13333333,  0.26666667, -0.6       ],
       [ 0.23529412,  0.35294118, -0.41176471],
       [ 0.57142857, -0.42857143,  0.        ]])

In [12]:
norm.fit(arr)

Normalizer(norm='l1')

In [13]:
arr

array([[ 2,  4, -9],
       [ 4,  6, -7],
       [12, -9,  0]])

In [14]:
df = pd.read_csv('wdbc.data', header = None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [15]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [16]:
df.replace(['?' , 'na' ,'nil' ' '] , np.nan , inplace=True)

In [17]:
df

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [18]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
dtype: int64

In [19]:
df.dropna(axis=1)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [20]:
df_cleaned = df.dropna(axis=0)
df_cleaned

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [21]:
df_cleaned

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [23]:
df_nums = df_cleaned.select_dtypes(include='number')

In [24]:
df_nums

,0,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
0,842302,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [25]:
normalize(df_nums , norm = 'l2')

array([[9.99996369e-01, 2.13580576e-05, 1.23233262e-05, ...,
        3.15087743e-07, 5.46239151e-07, 1.41160259e-07],
       [9.99996031e-01, 2.44148407e-05, 2.10914788e-05, ...,
        2.20766183e-07, 3.26401614e-07, 1.05659170e-07],
       [1.00000000e+00, 2.33568079e-07, 2.52073219e-07, ...,
        2.88253140e-09, 4.28583784e-09, 1.03889753e-09],
       ...,
       [9.99998817e-01, 1.79080951e-05, 3.02927295e-05, ...,
        1.52973969e-07, 2.39278041e-07, 8.43622310e-08],
       [9.99997103e-01, 2.22163821e-05, 3.16313828e-05, ...,
        2.85793265e-07, 4.40768706e-07, 1.33729678e-07],
       [9.99993447e-01, 8.36643179e-05, 2.64577624e-04, ...,
        0.00000000e+00, 3.09536413e-06, 7.58908677e-07]], shape=(569, 31))

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
scaler = StandardScaler()

In [31]:
print(scaler.fit(df_nums))

StandardScaler()

In [32]:
print(scaler.mean_)

[3.03718314e+07 1.41272917e+01 1.92896485e+01 9.19690334e+01
 6.54889104e+02 9.63602812e-02 1.04340984e-01 8.87993158e-02
 4.89191459e-02 1.81161863e-01 6.27976098e-02 4.05172056e-01
 1.21685343e+00 2.86605923e+00 4.03370791e+01 7.04097891e-03
 2.54781388e-02 3.18937163e-02 1.17961371e-02 2.05422988e-02
 3.79490387e-03 1.62691898e+01 2.56772232e+01 1.07261213e+02
 8.80583128e+02 1.32368594e-01 2.54265044e-01 2.72188483e-01
 1.14606223e-01 2.90075571e-01 8.39458172e-02]

In [34]:
print(scaler.scale_)

[1.24910677e+08 3.52095076e+00 4.29725464e+00 2.42776193e+01
 3.51604754e+02 1.40517641e-02 5.27663291e-02 7.96497253e-02
 3.87687325e-02 2.73901809e-02 7.05415588e-03 2.77068942e-01
 5.51163427e-01 2.02007710e+00 4.54510134e+01 2.99987837e-03
 1.78924359e-02 3.01595231e-02 6.16486075e-03 8.25910439e-03
 2.64374475e-03 4.82899258e+00 6.14085432e+00 3.35730016e+01
 5.68856459e+02 2.28123569e-02 1.57198171e-01 2.08440875e-01
 6.56745545e-02 6.18130785e-02 1.80453893e-02]

In [35]:
print(scaler.transform(df_nums))

[[-0.23640517  1.09706398 -2.07333501 ...  2.29607613  2.75062224
   1.93701461]
 [-0.23640344  1.82982061 -0.35363241 ...  1.0870843  -0.24388967
   0.28118999]
 [ 0.43174109  1.57988811  0.45618695 ...  1.95500035  1.152255
   0.20139121]
 ...
 [-0.23572747  0.70228425  2.0455738  ...  0.41406869 -1.10454895
  -0.31840916]
 [-0.23572517  1.83834103  2.33645719 ...  2.28998549  1.91908301
   2.21963528]
 [-0.24240586 -1.80840125  1.22179204 ... -1.74506282 -0.04813821
  -0.75120669]]

In [37]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
minmax = MinMaxScaler()

In [43]:
print(minmax.fit(df_nums))

MinMaxScaler(feature_range=(0, 5))

In [48]:
print(minmax.data_max_)

[9.11320502e+08 2.81100000e+01 3.92800000e+01 1.88500000e+02
 2.50100000e+03 1.63400000e-01 3.45400000e-01 4.26800000e-01
 2.01200000e-01 3.04000000e-01 9.74400000e-02 2.87300000e+00
 4.88500000e+00 2.19800000e+01 5.42200000e+02 3.11300000e-02
 1.35400000e-01 3.96000000e-01 5.27900000e-02 7.89500000e-02
 2.98400000e-02 3.60400000e+01 4.95400000e+01 2.51200000e+02
 4.25400000e+03 2.22600000e-01 1.05800000e+00 1.25200000e+00
 2.91000000e-01 6.63800000e-01 2.07500000e-01]

In [49]:
print(minmax.transform(df_nums))

[[4.57380213e-03 2.60518718e+00 1.13290497e-01 ... 4.56013746e+00
  2.99231224e+00 2.09431982e+00]
 [4.57498175e-03 3.21572247e+00 1.36286777e+00 ... 3.19587629e+00
  1.16794796e+00 1.11439066e+00]
 [4.62477442e-01 3.00747787e+00 1.95130200e+00 ... 4.17525773e+00
  2.01852947e+00 1.06716516e+00]
 ...
 [5.03825347e-03 2.27625538e+00 3.10618870e+00 ... 2.43642612e+00
  6.43603390e-01 7.59543487e-01]
 [5.03982812e-03 3.22282171e+00 3.31755157e+00 ... 4.55326460e+00
  2.48570865e+00 2.26157681e+00]
 [4.61318492e-04 1.84343793e-01 2.50760906e+00 ... 0.00000000e+00
  1.28720678e+00 5.03410731e-01]]